spring:
  application:
    name: mldncloud-config-server                  # 定义微服务名称
  cloud:                      # 进行SpringCloud的相关配置
    config:                   # 进行SpringCloudConfig的相关配置
      server:                     # 设置服务的连接地址
        encrypt:
          enabled: true 
        git:                  # 设置GIT连接地址
          uri: git@github.com:mldn/mldncloud.git
encrypt:
  keyStore:
    location: classpath:/keystore.jks   # keystore.jks的配置文件的路径
    password: mldnjava      # 设置store的密码 
    alias: mytestkey      # 别名
    secret: changeit      # keypass密码




server:
  port: 7501                                      # 服务端口
eureka:
  client:                                         # 客户端进行Eureka注册的配置
    service-url:                                  # 定义Eureka服务地址
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka
  instance:
    instance-id: config-7501.com                    # 显示主机名称

info:
  app.name: mldncloud-config-server
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$

