spring:
  rabbitmq:
    host: rabbitmq-single   # 消息主机
    port: 5672    # 连接端口
    username: mldn  # 用户名
    password: java # 密码
    virtual-host: /   # 虚拟主机
  sleuth:
    sampler:
      percentage: 1.0   # 定义抽样比率，默认为0.1
  application:
    name: mldncloud-zuul-gateway                  # 定义微服务名称
server:
  port: 9501                                      # 服务端口

security:
  basic:
    enabled: true
  user:
    name: zdmin
    password: mldnjava

zuul:
  prefix: /mldn-proxy          # 定义公共代理前缀
  ignored-services:             # 禁用微服务列表
    "*"
  routes: 
    mldncloud-dept-service: /dept-proxy/**


eureka:
  client:                                         # 客户端进行Eureka注册的配置
    service-url:                                  # 定义Eureka服务地址
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka
  instance:
    instance-id: gateway-9501.com                  # 显示主机名称
