server:
  port: 8601          # 配置监听端口号
spring:
  rabbitmq:
    host: rabbitmq-single   # 消息主机
    port: 5672    # 连接端口
    username: mldn  # 用户名
    password: java # 密码
    virtual-host: /   # 虚拟主机
  datasource: 
    url: jdbc:mysql://localhost:3306/zipkin # 连接地址
    username: root  # 用户名
    password: mysqladmin # 密码
    driver-class-name: org.gjt.mm.mysql.Driver # 驱动程序
    initialize: true # 初始化
  application:
    name: mldncloud-zipkin-server
zipkin: 
  storage:  # 设置zipkin收集的信息通过mysql进行存储
    type: mysql # 数据库存储
